media_kit_core_video/windows/CMakeLists.txt, media_kit_core_video/windows/angle_surface_manager.cc, media_kit_core_video/windows/video_output.cc
so turns out the brute force way can be the best way, the fixes 99% of flickers, to the degree that loading an 8k video with an gpu stress test running in the foreground is, while still not watchable, not flickering at all... mostly 
every now and then there is a rare flicker, however im fairly convinced that this is because of skia itself, as other elements of the app become troublesome anyways, like animations freezing. and I really don't think there is anything we can do with that.
this MIGHT be troublesome due to the extra glfinishes. meaning high refreshrate content might suffer from this, however I don't have a display to test that with unfortunately.
also fixes resize flicker that I was experiencing. 
all in all, 4k60 content is now flicker free
hopefully Addresses #10
=> Flickerfix mostly

README.md, media_kit_test/lib/main.dart, media_kit_video/lib/src/video.dart, media_kit_video/lib/src/video_controller.dart, media_kit_video/windows/angle_surface_manager.cc, media_kit_video/windows/media_kit_video_plugin.cc, media_kit_video/windows/thread_pool.h, media_kit_video/windows/video_output.cc, media_kit_video/windows/video_output.h, media_kit_video/windows/video_output_manager.cc, media_kit_video/windows/video_output_manager.h
~~Now Flutter UI feels much snappier than before & no longer feels "slowed down" when one or more videos are visible.~~
~~Technically, the correct place to do all the video rendering (& thus resize) etc. is on Flutter's render thread itself (exposed as callback in flutter::GpuSurfaceTexture & flutter::PixelBufferTexture). However, this slows down the UI too much. So, I decided to create our own ThreadPool & use it for all the video rendering purposes through one single thread.~~
All the operations involving ANGLE or EGL or libmpv must be performed on same single thread to prevent any race conditions or invalid ANGLE usage. Not doing so results in access violations & crashes (#17).
The following operations are performed through the ThreadPool:
* Rendering of video frame i.e. …
=> perf(win): use ThreadPool for video rendering & EGL/ANGLE usage synchronization

.github/workflows/ci.yml, README.md, media_kit_video/windows/CMakeLists.txt, media_kit_video/windows/angle_surface_manager.cc, media_kit_video/windows/angle_surface_manager.h, media_kit_video/windows/video_output.cc, media_kit_video/windows/video_output.h
Now two instances of `ID3D11Texture2D` are created inside `ANGLESurfaceManager`. First one for drawing onto using ANGLE/EGL (libmpv) & second one which gets copied from the first one upon every request. The `ID3D11Texture2D` requested by the public API & gets copied to right before every render request (ANGLESurfaceManager::Read). It's shared HANDLE is exposed in the `ANGLESurfaceManager::handle` getter. 
`ANGLESurfaceManager::Draw` & `ANGLESurfaceManager::Read` abstract the process of EGL context acquiring & rendering. A single mutex is also involved.
This removes any possible races & synchronization issues between libmpv & Flutter _i.e._ flickers (#10) without needing any redundant `glFinish` calls (#11).
- `ANGLESurfaceManager::Draw`:
- Call ANGLE/EGL/libmpv APIs in it's callback & …
=> perf(win): improve rendering synchronization & support stable channel

.github/workflows/ci.yml, media_kit/lib/src/libmpv/core/native_library.dart, media_kit_libs_windows_audio/analysis_options.yaml, media_kit_libs_windows_audio/windows/CMakeLists.txt, media_kit_libs_windows_video/analysis_options.yaml, media_kit_libs_windows_video/windows/CMakeLists.txt, media_kit_test/lib/main.dart
- Update libmpv in package:media_kit_libs_windows_video to merge latest changes at [mpv-player/mpv](https://github.com/mpv-player/mpv).
- libmpv dynamic library now uses name libmpv-2.dll on Windows.
The the relevant libmpv.dll.a links to libmpv-2.dll (previously mpv-2.dll). Thus, we needed update.
- Now DynamicLibrary.find caches the resolved dynamic library path.
=> build(win32): bump libmpv in package:media_kit_libs_windows_video

.gitmodules, README.md, media_kit/README.md, media_kit/lib/src/libmpv/core/initializer.dart, media_kit/lib/src/libmpv/core/initializer_isolate.dart, media_kit/lib/src/libmpv/core/initializer_native_event_loop.dart, media_kit/lib/src/platform_player.dart, media_kit_native_event_loop/.metadata, media_kit_native_event_loop/linux/CMakeLists.txt, media_kit_native_event_loop/pubspec.yaml, media_kit_native_event_loop/src/CMakeLists.txt, media_kit_native_event_loop/src/dart_api_types.h, media_kit_native_event_loop/src/media_kit_native_event_loop.cc, media_kit_native_event_loop/src/media_kit_native_event_loop.h, media_kit_native_event_loop/windows/.gitignore, media_kit_native_event_loop/windows/CMakeLists.txt, media_kit_test/lib/main.dart, media_kit_test/pubspec.yaml
I don't have much time to document how it'd work, implementation should be self-explanatory.
A drop-in solution to resolve the issue. Simply adding the package to `pubspec.yaml` will allow customers to use more than 8 instances of `Player` simultaneously without any issues. [`package:media_kit`](https://github.com/alexmercerind/media_kit/tree/main/media_kit) will switch to this implementation automatically if the shared library generated by this target is found. Otherwise, it will fallback to default [`Isolate` based event handling](https://github.com/alexmercerind/media_kit/blob/main/media_kit/lib/src/libmpv/core/initializer.dart).
```yaml
dependencies:
media_kit_native_event_loop: ^1.0.0
```
Closes #40.
=> package:media_kit_native_event_loop

media_kit/lib/src/libmpv/core/initializer.dart, media_kit/lib/src/libmpv/core/initializer_isolate.dart, media_kit/lib/src/libmpv/core/initializer_native_event_loop.dart, media_kit/lib/src/libmpv/core/native_library.dart, media_kit/lib/src/libmpv/player.dart
No need to manually at various places. [`package:media_kit_native_event_loop`](https://github.com/alexmercerind/media_kit/tree/main/media_kit_native_event_loop) follows the same.
Host system automatically handles it e.g. 
- Windows looking at `%PATH%` & executable directory etc.
- GNU/Linux using `LD_LIBRARY_PATH`.
Closes #47.
=> fix: improve libmpv discovery

media_kit/lib/src/libmpv/player.dart, media_kit/lib/src/models/player_log.dart, media_kit/lib/src/models/player_streams.dart, media_kit/lib/src/platform_player.dart, media_kit_test/lib/main.dart
As the title suggests, this adds support for mpv logs:
1. `media_kit`: Added a `log` stream to retrieve logs from mpv
2. `media_kit`: Added a new option in the `PlayerConfiguration` to choose the level of logs you want to get. Defaults to `none`.
3. `media_kit_test`: Changed the player configuration of `SimpleScreen` & `SimpleStream`, to pipe the logs of min level `warn` to the console in debug mode
---
@alexmercerind Feel free to modify the doc or code if you want 🙂
=> add mpv logs support

.github/workflows/ci.yml
Add CI universal build for macOS (amd64 & arm64).
I tested the artifact, it works.
I also added a condition on the release creation so that it only happens on the main branch: [.github/workflows/ci.yml#L82](https://github.com/birros/media_kit/blob/3a0817296155635dab491d4594fac9c89aa0df35/.github/workflows/ci.yml#L82)
@alexmercerind If it's ok with you, we can merge.
=> add CI build for macOS

media_kit_video/lib/src/video.dart
Adds optional `aspectRatio` argument to `Video` widget.
```dart
class _MyVideoState extends State<MyVideo> {
@override
Widget build(BuildContext context) {
return Video(
controller: controller,
// 🎉
aspectRatio: 1.0,
);
}
}
```
<hr></hr>
Implements feature requested in #60.
=> feat: aspect ratio in Video Widget

README.md, media_kit/README.md
I just added the doc for the setup and the implementation for macOS & iOS.
@alexmercerind I let you add the graphs (if you want).
For info iOS & macOS share a lot of code, maybe more in the future, I voluntarily duplicated some parts of the `TextureHW` code because they are likely to change a lot in the future. For the moment their logic is almost identical.
=> docs: update macOS & iOS doc

README.md, media_kit/CHANGELOG.md, media_kit/README.md, media_kit/pubspec.yaml, media_kit_libs_ios_video/CHANGELOG.md, media_kit_libs_ios_video/ios/.gitignore, media_kit_libs_ios_video/ios/Frameworks/.gitignore, media_kit_libs_ios_video/ios/Headers/mpv/.gitignore, media_kit_libs_ios_video/ios/Makefile, media_kit_libs_ios_video/pubspec.yaml, media_kit_libs_macos_video/CHANGELOG.md, media_kit_libs_macos_video/macos/.gitignore, media_kit_libs_macos_video/macos/Frameworks/.gitignore, media_kit_libs_macos_video/macos/Headers/mpv/.gitignore, media_kit_libs_macos_video/macos/Makefile, media_kit_libs_macos_video/pubspec.yaml, media_kit_video/CHANGELOG.md, media_kit_video/ios/.gitignore, media_kit_video/ios/Headers/mpv/.gitignore, media_kit_video/ios/Makefile, media_kit_video/macos/.gitignore, media_kit_video/macos/Headers/mpv/.gitignore, media_kit_video/macos/Makefile, media_kit_video/pubspec.yaml
Fix #103 & #104
pub don't keep dot files when publishing a package.
So I use mkdir to create required empty folders.
=> fix: pub for macOS & iOS

media_kit_test/lib/common/widgets.dart
Solved issues :
1. Slider glitching back and forth while seeking.
2. Disabled the slider to prevent the user from seeking even if the media is ended.
=> Fixed glitching slider while seeking in test project.

media_kit/lib/src/libmpv/player.dart, media_kit/lib/src/models/player_state.dart, media_kit/lib/src/models/player_streams.dart, media_kit/lib/src/platform_player.dart, media_kit_test/lib/common/widgets.dart
Added functionality to retrieve the last buffered placement in the player and implemented the necessary logic in the media_kit_test to test the changes. Please refer to the attached photo for reference.
Changes Made:
- Added code to retrieve the last buffered placement in the player.
- Implemented logic in the media_kit_test to test the changes.
- Attached a photo for reference.
=> feat: buffer stream & state

media_kit_libs_android_audio/android/build.gradle, media_kit_libs_android_video/android/build.gradle
- Support for Android <= 8.0.
- Add support for x86 (only emulators /w Flutter).
- Upgrade media_kit_native_event_loop shared object from dbbf48819f577e3289d645b66443f0add2773c48.
=> fix(android): bump dependencies

media_kit/lib/media_kit.dart, media_kit/lib/src/android_asset_loader.dart, media_kit/lib/src/libmpv/core/initializer.dart, media_kit/lib/src/libmpv/core/initializer_isolate.dart, media_kit/lib/src/libmpv/core/initializer_native_event_loop.dart, media_kit/lib/src/libmpv/core/native_library.dart, media_kit/lib/src/libmpv/entry_point.dart, media_kit/lib/src/libmpv/player.dart, media_kit/lib/src/media_kit.dart, media_kit/lib/src/platform_player.dart, media_kit/lib/src/player.dart, media_kit_native_event_loop/src/media_kit_native_event_loop.cc, media_kit_native_event_loop/src/media_kit_native_event_loop.h, media_kit_test/ios/Podfile.lock, media_kit_test/lib/main.dart, media_kit_test/lib/tests/05.stress_test.dart, media_kit_test/macos/Flutter/GeneratedPluginRegistrant.swift, media_kit_test/macos/Podfile.lock, media_kit_test/windows/flutter/generated_plugin_registrant.cc, media_kit_test/windows/flutter/generated_plugins.cmake, media_kit_video/common/darwin/Classes/plugin/TextureSW.swift, media_kit_video/ios/Classes/plugin/TextureHW.swift, media_kit_video/lib/src/video_controller_android.dart, media_kit_video/linux/video_output.cc, media_kit_video/macos/Classes/plugin/TextureHW.swift, media_kit_video/windows/video_output.cc
Adds new API `MediaKit.ensureInitialized`, this allows to:
- Handle libmpv & package:media_kit_native_event_loop discovery + loading in advance.
- Receive some additional initialization arguments etc.
- Expose ability to handle/catch any initialization errors to clients e.g. libmpv shared library not found etc.
- Dispose already running `Player` instances on hot-restart.
Other changes:
- Set `PlayerConfiguration.vo` to `null` by default.
Windows, GNU/Linux & Android embeddings now set it to `libmpv` when a new `VideoOutput` is created.
- Refactor libmpv `mpv_handle*` initialization into `InitializerIsolate` & `InitializerNativeEventLoop` classes.
=> feat/refactor: entry-point API

media_kit/lib/src/libmpv/player.dart, media_kit/lib/src/platform_player.dart
Added a configuration setting to the player to set [demuxer-lavf-o](https://mpv.io/manual/stable/#options-demuxer-lavf-o) with the value `protocol_whitelist=[file,tcp,tls,http,https]` this property allows the library to parse M3U8 files with the specified protocols, which should resolve issues with playing HTTPS M3U8 files.
```dart
final Player player = Player(
configuration: const PlayerConfiguration(
logLevel: MPVLogLevel.warn,
protocolWhitelist: ["file", "tcp", "tls", "http", "https", "crypto","data"],
),
)
```
```m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=674554,CODECS="avc1.640015,mp4a.40.2",RESOLUTION=426x240,FRAME-RATE=30,AUDIO="audio2"
https://api.omegastream.net/stream/company/processed-enterprise-media/bd413f82/video/57721636-0247-4588-8 …
```
=> fix HTTPS m3u8 file not loading

media_kit_video/linux/video_output.cc
This PR enables support for hardware acceleration using VAAPI, which resolves #143.
=> VAAPI hardware acceleration support

media_kit_video/windows/video_output.cc
Last pull-request #137 introduced some synchronization fixes & improvements for Windows.
This brings few more performance improvements on-top of #137.
=> perf(windows): VideoOutput::Resize: delete texture objects in background

media_kit_native_event_loop/common/darwin/Podspec/media_kit_utils.rb, media_kit_native_event_loop/ios/media_kit_native_event_loop.podspec, media_kit_native_event_loop/macos/media_kit_native_event_loop.podspec, media_kit_video/common/darwin/Podspec/media_kit_utils.rb, media_kit_video/ios/media_kit_video.podspec, media_kit_video/macos/media_kit_video.podspec
Fix #159, handling `PWD_FALLBACK` manually set in a CI.
Also, prevent future issues like #172.
=> fix(darwin): fix pubspec.lock search in podspec

media_kit/lib/src/player/libmpv/core/initializer_native_event_loop.dart, media_kit/lib/src/player/libmpv/core/task_queue.dart, media_kit/lib/src/player/libmpv/player/real.dart, media_kit/pubspec.yaml
- share synchronization `Lock` across all `libmpvPlayer`(s)
- throw `AssertionError` if any instance method is called after `dispose`
=> fix: safer Player.dispose

media_kit/lib/src/player/libmpv/player/real.dart, media_kit/test/src/player/player_test.dart
- fix: set/emit completed=false upon seek (#221)
- test: player-seek-after-completed & more strict checks
=> fix: set/emit completed=false upon seek (#221)

media_kit/lib/src/models/player_state.dart
Changing the default volume in player state from 1 to 100,
=> fix: default volume 1 to 100 in player state

media_kit_test/android/app/build.gradle, media_kit_video/lib/src/video/video_texture.dart, media_kit_video/lib/src/video/video_web.dart, media_kit_video/pubspec.yaml
This PR migrates the project from the outdated `wakelock` package to `wakelock_plus`. The `wakelock` package currently has an outdated win32 version and hasn’t been updated in 12 months, while `wakelock_plus` is managed by the Flutter community and provides the latest updates and improvements.
- Updated package dependencies in `pubspec.yaml` to use `wakelock_plus` instead of `wakelock`.
- Updated import statements throughout the project to import `wakelock_plus` instead of `wakelock`.
- Updated code usages of `wakelock` API to use the corresponding `wakelock_plus` API.
- Removed any unnecessary code related to `wakelock` package.
- Ran existing tests to ensure that the functionality is preserved after the migration.
- Tested on both Android and iOS devices/emulators to ensure proper …
=> fix(wakelock): Migrate to wakelock_plus

libs/windows/media_kit_libs_windows_audio/CHANGELOG.md, libs/windows/media_kit_libs_windows_audio/README.md, libs/windows/media_kit_libs_windows_video/CHANGELOG.md, libs/windows/media_kit_libs_windows_video/README.md, libs/windows/media_kit_libs_windows_video/example/README.md, libs/windows/media_kit_libs_windows_video/pubspec.yaml, libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt, media_kit/lib/src/player/native/player/real.dart, media_kit/lib/src/player/platform_player.dart, media_kit/lib/src/player/web/player/real.dart, media_kit/test/src/player/player_test.dart, media_kit_video/lib/src/video_controller/android_video_controller/real.dart, media_kit_video/lib/src/video_controller/native_video_controller/real.dart, media_kit_video/lib/src/video_controller/utils/query_decoders.dart, media_kit_video/lib/src/video_controller/video_controller.dart
Re-work things based on https://github.com/alexmercerind/media_kit/pull/287#issuecomment-1641110217.
Additionally handle a condition if media_kit_libs_***_audio are used with `VideoController` (audio still plays):
=> perf: vid=no until `VideoController` attach; build(windows): bump native libraries

media_kit_video/lib/media_kit_video_controls/src/controls/material_desktop.dart
This allows you to wrap your Video widget with additional GestureDetector to add onTap callbacks. Right now if you wrap this widget with GestureDetector then you won't be able to execute any onTap callbacks. Of course this could be done with Listener widget, but then it will cover whole player, even play/resume buttons, etc., what's not good
=> Do not add onTapUp callback if toggleFullscreenOnDoublePress is disabled

media_kit/lib/src/player/native/core/initializer_isolate.dart
- fix: remove `TaskQueue`/`LockExt` logic in `NativePlayer.dispose`
- fix: `InitializerIsolate` reduce `Isolate.kill` delay
=> fix: remove TaskQueue/LockExt logic; fix: InitializerIsolate reduce Isolate.kill delay 

media_kit/lib/media_kit.dart
- Exports `PlayerState` and `PlayerStream` since they are public APIs and their `Type` cannot be referenced outside. (e.g. `final PlayerState state = player.state;`)
- Sort exports alphabetically.
=> feat: Improve model exports

README.md, libs/linux/media_kit_libs_linux/linux/CMakeLists.txt, media_kit/README.md, media_kit_test/linux/CMakeLists.txt, media_kit_video/linux/video_output.cc
A continuation of #319. Originally explored as part of #68.
For enabling [mimalloc](https://github.com/microsoft/mimalloc), one must add following line to `linux/CMakeLists.txt`:
https://github.com/media-kit/media-kit/blob/d02a97ce70b316207db024401fb99e3f4509a250/media_kit_test/linux/CMakeLists.txt#L92-L94
This replaces all `malloc`/`calloc`/`free`/`new`/`delete` calls in application (for the good).
=> feat(linux): mimalloc support

README.md, libs/ios/media_kit_libs_ios_audio/CHANGELOG.md, libs/ios/media_kit_libs_ios_audio/example/README.md, libs/ios/media_kit_libs_ios_audio/ios/Makefile, libs/ios/media_kit_libs_ios_audio/pubspec.yaml, libs/ios/media_kit_libs_ios_video/CHANGELOG.md, libs/ios/media_kit_libs_ios_video/example/README.md, libs/ios/media_kit_libs_ios_video/ios/Makefile, libs/ios/media_kit_libs_ios_video/pubspec.yaml, libs/macos/media_kit_libs_macos_audio/CHANGELOG.md, libs/macos/media_kit_libs_macos_audio/example/README.md, libs/macos/media_kit_libs_macos_audio/macos/Makefile, libs/macos/media_kit_libs_macos_audio/pubspec.yaml, libs/macos/media_kit_libs_macos_video/CHANGELOG.md, libs/macos/media_kit_libs_macos_video/example/README.md, libs/macos/media_kit_libs_macos_video/macos/Makefile, libs/macos/media_kit_libs_macos_video/pubspec.yaml, media_kit/CHANGELOG.md, media_kit/README.md
Flutter or Windows changes the encoding of the `create_framework_symlinks.sh` script, making it unusable.
Fix #338
=> fix(darwin): fix CRLF added by Flutter packaging

media_kit/lib/src/player/native/player/real.dart, media_kit/test/src/player/player_test.dart
A new forbidden API that might be useful in some advanced use-cases. I have added relevant unit-tests.
**Example Usage:**
```dart
import 'package:media_kit/media_kit.dart';
Future<void> main() async {
MediaKit.ensureInitialized();
final player = Player();
await (player.platform as NativePlayer).observeProperty(
'demuxer-cache-state',
(data) async {
print(data);
},
);
await player.open(Media('https://user-images.githubusercontent.com/28951144/229373695-22f88f13-d18f-4288-9bf1-c3e078d83722.mp4'));
}
```
**Example Output:**
```
{"cache-duration":0.000000,"eof":false,"underrun":true,"idle":false,"total-bytes":0,"fw-bytes":0,"raw-input-rate":2362,"debug-low-level-seeks":0,"debug-byte-level-seeks":0,"bof-cached":false,"eof-cached":false,"seekable-ranges":[]} …
```
=> feat: `NativePlayer.observeProperty` & `NativePlayer.unobserveProperty`

media_kit_video/lib/media_kit_video_controls/src/controls/methods/fullscreen.dart
Adds await to exitFullscreen() removing race condition? when trying to exit fullscreen and then pop the context of another widget.
=> fix: Add await to pop() when exiting fullscreen

media_kit/CHANGELOG.md, media_kit/lib/src/player/native/player/real.dart, media_kit/lib/src/player/platform_player.dart, media_kit/lib/src/player/web/player/real.dart, media_kit/test/src/player/player_test.dart, media_kit_video/lib/src/video/video_texture.dart, media_kit_video/lib/src/video/video_web.dart
The behavior of `Player` is _mostly_ still the same.
Only 2 changes can be seen (which I believe are favorable) in tests, as it can be seen:
- `buffering` will be restored back to `false` once `Player.open` is called.
- `tracks` will be cleared once `Player.open` is called.
Primarily this is done to reset previously playing `Media`'s state (while newly opened buffering for example) e.g.
- [Last frame stuck.](https://github.com/media-kit/media-kit/issues/356#issuecomment-1675757193)
- [~~Last subtitles stuck.~~ A different fix & test will be needed.](https://github.com/media-kit/media-kit/issues/394#issuecomment-1694491967)
<hr>
I was already familiar with the issues & it'll be cool to have these resolved.
=> fix: reset `Player` state/stream upon `Player.open`; fix: hide last video's frame upon `Player.open`

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart, media_kit_video/lib/media_kit_video_controls/src/controls/material_desktop.dart
any themes defined in the app is overridden in controls 
using the new changes the colors defined by media_kit are still the same but we dont override the user themes
=> fix: theme override

libs/ios/media_kit_libs_ios_audio/ios/Makefile, libs/ios/media_kit_libs_ios_video/ios/Makefile, libs/macos/media_kit_libs_macos_audio/macos/Makefile, libs/macos/media_kit_libs_macos_video/macos/Makefile
- fix iOS HDR (#372)
- ~~fix HLS MP4 seek (#395)~~
- fix VP9 macOS Intel freezes
- fix image based subtitles
- fix subtitles in m3u8 (#394)
- add AV1 support (#429)
---
As there are a lot of changes, particularly patches, there's a risk of introducing bugs, so I'm going to keep this PR open for a few days so that everyone can test it.
=> build(darwin): bump libs

media_kit_video/windows/utils.cc
Closes #439 
This change corrects the width and height parameters passed to the SetWindowPos function
Previously, the right and bottom coordinates of the monitor were incorrectly used as the window size. Now, the width and height are correctly calculated as the differences between the right and left coordinates and the bottom and top coordinates.
=> [Windows] Fix fullscreen for non-primary monitors

media_kit_video/common/darwin/Classes/plugin/ResizableTextureProtocol.swift, media_kit_video/common/darwin/Classes/plugin/SafeResizableTexture.swift, media_kit_video/common/darwin/Classes/plugin/TextureSW.swift, media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift, media_kit_video/common/darwin/Classes/plugin/VideoOutputManager.swift, media_kit_video/common/darwin/Classes/plugin/Worker.swift, media_kit_video/ios/Classes/plugin/TextureHW.swift, media_kit_video/ios/Classes/plugin/gles/OpenGLESHelpers.swift, media_kit_video/macos/Classes/plugin/TextureHW.swift, media_kit_video/macos/Classes/plugin/gl/OpenGLHelpers.swift
Many classes don't `deinit` and keep references to sub classes who cannot `deinit` itself, etc…
When `VideoOutput` is destroyed, this prevents [ARC](https://en.wikipedia.org/wiki/Automatic_Reference_Counting) from releasing `CVOpenGL(ES)TextureCache`, who keeps direct / indirect references to `IOSurface` used by `CVPixelBuffer`.
Also, we discovered that `glDeleteTextures` doesn't release `CVOpenGL(ES)Texture`, `CVOpenGL(ES)TextureCache` must be released to delete references.
After `Texture(HW/SW)` release, many `IOSurface` persist in memory. This is not a bug or a memory leak, but expected behavior.
With Xcode, we find that `IOSurface` are still referenced by `CVMetalTextureCache`, itself referenced by [FlutterDarwinContextMetalSkia](https://github.com/flutter/engine/blob/3.13.2/shell/plat …
=> fix(darwin): fix memory leaks

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart
`PageViews` and `ListViews` (and most probably many other scrollable widgets) use the `Scrollable` widget which uses `HorizontalDragGestureRecognizer`. If any of these two widgets are used as a parent to `MaterialSeekBar`, horizontal drag gestures are caught by `GestureDetectors` used in these widgets containing a `Scrollable` since we only catch `Pan` gestures in `MaterialSeekBar`.
If one video is used for each page in a `PageView`, seeking the `MaterialSeekBar` leads to swiping and going to the next page because of this.
https://github.com/media-kit/media-kit/assets/77285023/a1963d1b-8b6a-4829-aa8c-7e21e47d6286
=> [Bug fix] Catch horizontalDragUpdate in MaterialSeekBar

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart
Uses the default colour if parameter is not passed.
=> feat(video-controls): add 'backdropColor' parameter to MaterialVideoControlsThemeData to configure backdrop color that comes up with controls

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart, media_kit_video/lib/media_kit_video_controls/src/controls/material_desktop.dart
Sets the state of the controls CircularProgressIndicator to a constant value when we're not buffering.
Fixes #472
=> fix: High gpu usage during idle

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart
The green colour represents the seekbar's tap area. 
The tap area is only on the top
The tap area is even on both top and bottom
=> feat(material-seekbar): Center the seek bar within its parent container for improved tap area

media_kit/lib/src/media_kit.dart
Handle situations like: https://github.com/media-kit/media-kit/issues/498#issuecomment-1737223715
=> feat: prevent multiple calls to `MediaKit.ensureInitialized`

media_kit/lib/src/player/native/player/real.dart
Now that `setProperty`, `observeProperty` & `unobserveProperty` are part of public API...
Let's add last piece of the puzzle.
=> feat: `NativePlayer.command`

media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift
Ref: https://github.com/flutter/flutter/issues/135345#issuecomment-1774328128
<hr>
The macOS & iOS side is built by @birros. Let's see if this is right...
=> fix(darwin): move `FlutterTextureRegistry.register` to main thread

media_kit/lib/src/models/media/media_web.dart
This pull request updates the error handling for HTTP headers in the web-specific implementation of our Media class. The adjustment is made to prevent unsupported HTTP header operations on web platforms more effectively.
In the current architecture, the `DataSource` class  https://github.com/media-kit/media-kit/blob/dad52462dd56643ba27d4c581bbcff0fce8fbde1/video_player_media_kit/lib/src/media_kit_video_player.dart#L90, defaults to an empty map if no headers are provided. The prior check in our code did not handle this default case, potentially leading to unintended behavior when an empty map is incorrectly treated as a valid input.
I've refined the HTTP header checks to throw an `UnsupportedError` only when `httpHeaders` is not null and contains one or more key-value pairs. This ensures …
=> fix: added check for http headers not empty on web

media_kit/lib/src/player/native/player/real.dart
mpv allows the use of `[+|-][[hh:]mm:]ss[.ms]` for `start` and `end`. Currently, the implementation drops the `ms` part.
This PR adds support for milliseconds in `start` and `end` for `Media`.
=> Add support for milliseconds in `start` and `end` for `Media`

media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift
Just a little optimization, because these calls to `MPVHelpers.getVideoOutParams` are not allowed at this time (in render callback), it causes some jank (at end of looping video is most obvious). Personally I work around it by eagerly using setSize. However, we can also take a simple optimization to avoid calling it twice for both width and height when it returns both.
=> Only one getVideoOutParams

media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift
I swapped the dimensions by mistake in https://github.com/media-kit/media-kit/pull/814
=> Fix swapped iOS texture dimensions

media_kit_video/lib/media_kit_video_controls/src/controls/methods/fullscreen.dart
Using a plain Material means that functionality that's tied to the nearest Scaffold, suck as SnackBars, won't actually be displayed on the page.
=> fix: Use a Scaffold as the outermost widget on fullscreen video pages

media_kit/lib/src/player/native/player/real.dart, media_kit/lib/src/player/platform_player.dart, media_kit/lib/src/player/player.dart, media_kit/lib/src/player/web/player/real.dart
On the native backend, this is essentially available for free: we just need to swap the flag given to the `screenshot-raw` command.
This option is simply ignored by the web backend.
=> feat: Add support for including libass subtitles in screenshots

media_kit/lib/src/models/player_state.dart, media_kit/lib/src/models/player_stream.dart, media_kit/lib/src/player/native/player/real.dart, media_kit/lib/src/player/platform_player.dart
fixing https://github.com/media-kit/media-kit/issues/755 
using the property of cache-buffering-state which returns the percentage of the buffering
=> chore: adding buffering Percentage state and streams

media_kit/lib/src/player/web/player/real.dart
Use hls.js isHLSSupported check only.
In relation to issue https://github.com/media-kit/media-kit/issues/880.
This fixes playing HLS m3u8 stream on Chrome on Android using Flutter Web.
=> Fix application/vnd.apple.mpegurl type HLS check for Chrome on Android

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart
`brightnessIndicatorBuilder` is called with `_volumeValue` instead of `_brightnessValue`
=> fix: wrong value in brightness builder callback

media_kit/lib/src/player/native/player/real.dart, media_kit/test/src/player/player_test.dart
This removes all noticeable blocking of dart/ui thread
Some notes/questions for @alexmercerind 
1. I replaced the "play() -> get_property -> playOrPause" pattern with just set_property('pause', false). I got bad race conditions with the old way. Not sure why you changed to it originally?
2. I can move `seek` back to the main thread now :)
3. I didn't change screenshot() since it has one-off use of command-with-result. But also it uses `package:image` to do some conversion in dart-space, so other Isolate is still a good idea.
4. I didn't implement getProperty. Because the memory ownership there gets a little more complicated. But after rebasing my change here, I see there is now NativePlayer.getProperty. Can think about it some more...
=> Asynchronous setProperty / command

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart
Resolved an issue where long pressing to speed up video playback would incorrectly reset the speed to 1.0x when the user was using a non-default speed (e.g., 1.25x, 1.5x).
=> fix:long press video speed reset issue

media_kit/lib/src/player/native/player/real.dart, media_kit_video/lib/media_kit_video_controls/src/controls/material.dart, media_kit_video/lib/media_kit_video_controls/src/controls/material_desktop.dart, media_kit_video/lib/src/video_controller/android_video_controller/real.dart, media_kit_video/lib/src/video_controller/native_video_controller/real.dart
- Prevent querying `mpv_get_property` on each render.
- Not changing native code to prevent any potential issues (happens to be very stable).
=> fix: set width/height from `VideoParams` in `NativeVideoController`

media_kit/lib/src/player/native/player/real.dart, media_kit/lib/src/player/native/utils/native_reference_holder.dart
The [`.value` getter](https://api.flutter.dev/flutter/dart-ffi/AbiSpecificIntegerPointer/value.html) can return integer value not equal to the actual address (especially on 32-bit systems). The [`.address` getter](https://api.flutter.dev/flutter/dart-ffi/Pointer/address.html) is now being used for accessing the raw integer address.
Primarily an issue with signed/unsigned nature of things.
=> fix: `NativeReferenceHolder` on 32-bit systems

media_kit/lib/src/player/native/player/real.dart
Property callback exception causes the player to freeze
=> fix: catch observe property callback exception

libs/ios/media_kit_libs_ios_audio/ios/Makefile, libs/ios/media_kit_libs_ios_video/ios/Makefile, libs/macos/media_kit_libs_macos_audio/macos/Makefile, libs/macos/media_kit_libs_macos_video/macos/Makefile, media_kit_video/common/darwin/Makefile
Hi everyone,
Small updates in the libs installation scripts to support the GNU versions of `sed` and `tar`.
Required for everyone who, like me, chooses to replace macOS native tools with their GNU equivalents.
=> build(darwin): add GNU env support

media_kit/lib/src/player/native/player/real.dart, media_kit_test/macos/Podfile.lock, video_player_media_kit/example/macos/Podfile.lock, video_player_media_kit/example/macos/Runner.xcodeproj/project.pbxproj, video_player_media_kit/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, video_player_media_kit/example/macos/Runner/AppDelegate.swift, video_player_media_kit/lib/src/media_kit_video_player.dart
i was testing video_player_media_kit to try out the seek without switching fully to media_kit i found out if the error stream throws any error even if its not critical (the sound will play but the video will be black and nothing will work as in ui wise no commands nor streams) but the sound works (so video got loaded correctly )
when i commented that part it works correctly, so i was thinking is it needed and if yes can we limit it to critical errors?
=> fix: video_player black screen

media_kit/lib/src/player/web/player/real.dart
VideoElement errors are passed to PlayerStream.error stream as error event instead of data event. Because of this, it becomes inconvenient to handle errors when using web and native.
Closes https://github.com/media-kit/media-kit/issues/991
=> fix: pass VideoElement errors as data event to error stream [web]

media_kit/lib/src/player/native/core/execmem_restriction.dart, media_kit/lib/src/player/native/core/initializer.dart, media_kit/lib/src/player/native/core/initializer_isolate.dart
On Linux-based systems using NativeCallables requires creating executable memory mappings (Dynamic Code Loading), otherwise the Dart VM crashes.
This PR adds a check for DCL and fallbacks to the isolate-based event loop, when DCL is disabled.
Plays fine on both my devices, but the isolate event loop had most likely race conditions, with the fix I can't reproduce a crash anymore.
Fixes #1015
=> Fix crashes on systems where DCL is restricted

libs/linux/media_kit_libs_linux/linux/CMakeLists.txt
Let's say we are under Linux filesystem and we have a Flutter project located under the following path : `/folder1/folder2/folder with spaces/flutter_example` that consumes `media_kit_libs_linux`
If we tried to build the project, an error will be occured :
```
[  +10 ms] cd "/folder1/folder2/folder with spaces/flutter_example/build/linux/x64/release/mimalloc" &&
/usr/local/bin/cmake -E tar xzf "/folder1/folder2/folder\ with\ spaces/flutter_example/build/linux/x64/release/mimalloc-2.1.2.tar.gz" && mkdir -p out/release && cd out/release && /usr/local/bin/cmake ../../mimalloc-2.1.2 && make
[   +1 ms] CMake Error: Problem with archive_read_open_file(): Failed to open
'/folder1/folder2/folder\ with\ spaces/flutter_example/build/linux/x64/release/mimalloc-2.1.2.tar.gz'
[   +4 ms] CMake Error: …
```
=> Extracting Mimalloc archive for projects located under folders with spaces in Linux

media_kit/lib/src/player/native/core/fallback_bitrate_handler.dart, media_kit/lib/src/player/native/player/real.dart, media_kit/lib/src/player/native/utils/native_reference_holder.dart, media_kit/lib/src/values.dart, media_kit/test/src/player/player_test.dart
It is too expensive to iterate through returned `mpv_node*`.
=> perf: optimize playlist state/stream in `NativePlayer`

media_kit/lib/src/models/media/media_web.dart, media_kit/lib/src/player/web/player/real.dart, media_kit/lib/src/player/web/utils/hls.dart
Use the xhrSetup option in hls.js to set the http headers for media when on the web.
Fixes https://github.com/media-kit/media-kit/issues/1042
Things used:
- https://github.com/video-dev/hls.js/blob/master/docs/API.md#xhrsetup
=> fix: pass http headers to hls.js

media_kit/pubspec.yaml, media_kit/test/src/player/player_test.dart, media_kit_test/pubspec.yaml, media_kit_video/pubspec.yaml
I'm not fully sure why it worked on 1.0.0, there's a few methods that work completely different under web 1.0.0 that break everything. I'm guessing it was working because lock file?
=> fix: bump web to 1.1.0

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart
this makes the controls come up in instant instead of the sides being slow due to waiting for double tap without breaking double tap
=> Fix: improve responsiveness of showing controls on mobile

video_player_media_kit/lib/src/media_kit_video_player.dart
related to this issue https://github.com/media-kit/media-kit/issues/1064 just improving developer experience
=> fix: add null checks for uri and textureId in MediaKitVideoPlayer

README.md, libs/linux/media_kit_libs_linux/CHANGELOG.md, libs/linux/media_kit_libs_linux/linux/CMakeLists.txt, libs/linux/media_kit_libs_linux/pubspec.yaml, media_kit/README.md
In some cases, users of the plugin might prefer to use a dynamically linked version of mimalloc. This PR introduces a new CMake option allowing to dynamically link mimalloc. Unlike #883 , this PR does **not** change the default behavior but simply adds an additional CMake option.
**The default behavior of the plugin is not changed.**
If users set the CMake option :
```cmake
set(MIMALLOC_USE_STATIC_LIBS OFF)
```
This plugin will now link against the system-provided mimalloc.
Users might prefer this in case they try to reduce installation size or aim to comply with distributor-specific dependency management requirements.
Unless this option is set to `OFF`, the behavior of the plugin won't change.
Thanks a lot for your amazing work 🎉 !
=> chore: refactor mimalloc import

media_kit_video/linux/include/media_kit_video/video_output.h
=> fix(linux+video): Default video output resolution to zeros

media_kit_video/pubspec.yaml
After submission of our latest update in the app store we got the following message:
> We noticed one or more issues with a recent submission for App Store review for the following app:
> 
> <redacted>
> 
> Although submission for App Store review was successful, you may want to correct the following issues in your next submission for App Store review. Once you've corrected the issues, upload a new binary to App Store Connect.
> 
> ITMS-91061: Missing privacy manifest - Your app includes “Frameworks/wakelock_plus.framework/wakelock_plus”, which includes wakelock, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. Starting February 12, 2025, if a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must …
=> fix: upgrade wakelock_plus to a version with a privacy manifest (iOS)

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart, media_kit_video/lib/media_kit_video_controls/src/controls/material_desktop.dart, media_kit_video/lib/media_kit_video_controls/src/controls/methods/fullscreen.dart, media_kit_video/lib/src/video/video_texture.dart, media_kit_video/lib/src/video/video_web.dart, media_kit_video/lib/src/video_view_parameters.dart
Replaces https://github.com/media-kit/media-kit/pull/1145
@james-lawrence feel free to check it out too
This pull request introduces a `FocusNode` to the `Video` widget and its associated classes to enable keyboard input handling. The changes span multiple files and ensure that the `FocusNode` is properly integrated and propagated through the various components.
Key changes include:
* [`media_kit_video/lib/src/video/video_texture.dart`](diffhunk://#diff-58c3e321a1bbd8f45488fca2cfcca646a8a0b61283bb3ba88a44257ef9fb95d1R116-R118): Added a `FocusNode` to the `Video` widget and propagated it through the `VideoState` class. This ensures that the `FocusNode` is properly managed and updated. [[1]](diffhunk://#diff-58c3e321a1bbd8f45488fca2cfcca646a8a0b61283bb3ba88a44257ef9fb95d1R116-R118) …
=> feat: Add FocusNode support for video controls and parameters

media_kit/lib/src/player/native/player/real.dart
It's not a good idea to use 0 for all of them.
=> fix: unique reply user data in mpv_observe_property

media_kit_video/windows/media_kit_video_plugin.cc, media_kit_video/windows/media_kit_video_plugin.h
fixes #1212
This PR builds on the approach introduced in flutter/packages#5884, using PostMessage and a top-level Window Proc Delegate to marshal work onto the main thread that owns the target HWND. It resolves the long-standing warning described in issue #1212.
@alexmercerind 
I’m not deeply versed in the Win32 API, so any corrections, optimizations, or style suggestions are very welcome. Thank you for your feedback!
=> fix[windows]: run method call on main thread

.gitignore, media_kit_test/lib/common/globals.dart, media_kit_video/android/src/main/java/com/alexmercerind/media_kit_video/VideoOutput.java, media_kit_video/lib/src/video_controller/android_video_controller/real.dart
- Remove unnecessary complexity.
- Fix an issue that caused video output to be stuck on black screen randomly.
- Ensure libmpv does not fallback to `mediacodec-copy` (if `vo=auto` is used) during various operations e.g. opening/switching media in `Player`.
```
PlayerLog(prefix: vd, level: info, text: Using hardware decoding (mediacodec).)
```
=> refactor(android): AndroidVideoController impl
