.github/workflows/ci.yml, media_kit_core_video/lib/video.dart, media_kit_core_video/lib/video_controller.dart, media_kit_core_video/windows/CMakeLists.txt, media_kit_core_video/windows/angle_surface_manager.cc, media_kit_core_video/windows/angle_surface_manager.h, media_kit_core_video/windows/video_output.cc, media_kit_core_video/windows/video_output.h, media_kit_core_video/windows/video_output_manager.cc, media_kit_core_video/windows/video_output_manager.h
=> fix(win): resize texture & EGLSurface on render thread

media_kit_test/lib/main.dart, media_kit_video/windows/video_output.cc
=> fix: free ANGLESurfaceManager through thread pool

media_kit_native_event_loop/CHANGELOG.md, media_kit_native_event_loop/pubspec.yaml, media_kit_native_event_loop/src/media_kit_native_event_loop.cc, media_kit_native_event_loop/src/media_kit_native_event_loop.h
=> fix: broken hot restart when using native_event_loop (macOS)

.tool-versions, media_kit/example/main.dart, media_kit/lib/media_kit.dart, media_kit/lib/src/libmpv/player.dart, media_kit/lib/src/models/player_error.dart, media_kit/lib/src/models/player_log.dart, media_kit/lib/src/models/player_state.dart, media_kit/lib/src/models/player_streams.dart, media_kit/lib/src/models/track.dart, media_kit/lib/src/platform_player.dart, media_kit/lib/src/player.dart, media_kit_test/lib/main.dart
Alternative to #55.
Overall design is similar to existing audio device enumeration/selection API. See following code snippet for more details.
Everything is strongly typed & follows best practices AFAIK.
```dart
final player = Player();
// Get currently available video, audio and subtitle tracks either using state or stream subscription:
player.streams.tracks.listen((e) {
// All video tracks.
for (final video in e.video) {
print(video.id);
print(video.title);
print(video.language);
}
// All audio tracks.
for (final audio in e.audio) {
print(audio.id);
print(audio.title);
print(audio.language);
}
// All subtitle tracks.
for (final subtitle in e.subtitle) {
print(subtitle.id);
print(subtitle.title);
print(subtitle.language);
}
});
final List<VideoTrack> videos = player.state.tracks.video; …
```
=> feat: track selection & events

media_kit_video/common/darwin/Classes/VideoOutput.swift
Fix #98
Force software rendering in the iOS simulator, due to OpenGL ES incompatibility.
=> fix iOS simulator

media_kit_libs_android_audio/android/build.gradle
Fixed android audio build, looks like by mistake this line was removed.
=> fix: android audio build

README.md, media_kit/CHANGELOG.md, media_kit/README.md, media_kit/pubspec.yaml, media_kit_libs_android_audio/CHANGELOG.md, media_kit_libs_android_audio/android/build.gradle, media_kit_libs_android_audio/android/src/main/AndroidManifest.xml, media_kit_libs_android_audio/example/README.md, media_kit_libs_android_audio/pubspec.yaml, media_kit_libs_android_video/CHANGELOG.md, media_kit_libs_android_video/android/build.gradle, media_kit_libs_android_video/android/src/main/AndroidManifest.xml, media_kit_libs_android_video/example/README.md, media_kit_libs_android_video/pubspec.yaml, media_kit_libs_macos_audio/CHANGELOG.md, media_kit_libs_macos_audio/example/README.md, media_kit_libs_macos_audio/pubspec.yaml, media_kit_libs_macos_video/CHANGELOG.md, media_kit_libs_macos_video/example/README.md, media_kit_libs_macos_video/pubspec.yaml, media_kit_video/CHANGELOG.md, media_kit_video/example/pubspec.lock, media_kit_video/lib/src/video_controller_android.dart, media_kit_video/pubspec.yaml
- perf(android): enable `extractNativeLibs` & reduce APK size
- fix(android): revert to `--vo=mediacodec_embed`
- fix(android): `package:ffmpeg_kit_flutter` compatibility
=> fix(android): revert to using --vo=mediacodec_embed in enableHardwareAcceleration

media_kit/lib/src/player/libmpv/player/real.dart, media_kit/test/src/player/player_test.dart
switched to core-idle instead of paused-for-cache, for buffering state
a fix for https://github.com/alexmercerind/media_kit/issues/227
=> fix: buffering not true during starting of stream playback

README.md, media_kit/README.md, media_kit_video/lib/media_kit_video.dart
=> fix: export subtitle_view.dart [skip ci]

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart, media_kit_video/lib/media_kit_video_controls/src/controls/material_desktop.dart, media_kit_video/lib/src/utils/wakelock.dart, media_kit_video/lib/src/video/video_texture.dart, media_kit_video/lib/src/video/video_web.dart
- Sync wakelock state with playing state
- Manage concurrent wakelock calls
=> feat: improve wakelock behavior

README.md, libs/android/media_kit_libs_android_audio/android/build.gradle, libs/android/media_kit_libs_android_video/android/build.gradle, media_kit/README.md, media_kit/lib/src/models/track.dart, media_kit/lib/src/player/native/player/real.dart, media_kit/lib/src/player/native/utils/android_helper.dart, media_kit/lib/src/player/native/utils/temp_file.dart, media_kit/lib/src/player/player.dart, media_kit/lib/src/player/web/player/real.dart, media_kit/pubspec.yaml, media_kit/test/src/player/player_test.dart
```dart
await player.open(
Media(
'https://www.iandevlin.com/html5test/webvtt/v/upc-tobymanley.theora.ogg',
),
);
await player.setSubtitleTrack(
SubtitleTrack.data(
'''WEBVTT FILE
1
00:00:03.500 --> 00:00:05.000 D:vertical A:start
Everyone wants the most from life
2
00:00:06.000 --> 00:00:09.000 A:start
Like internet experiences that are rich <b>and</b> entertaining
3
00:00:11.000 --> 00:00:14.000 A:end
Phone conversations where people truly <c.highlight>connect</c>
4
00:00:14.500 --> 00:00:18.000
Your favourite TV programmes ready to watch at the touch of a button
5
00:00:19.000 --> 00:00:24.000
Which is why we are bringing TV, internet and phone together in <c.highlight>one</c> super package
6
00:00:24.500 --> 00:00:26.000
<c.highlight>One</c> simple way to get everything
7
00:00:26.500 …
```
=> feat/refactor: SubtitleTrack.data support in Player

README.md, media_kit/CHANGELOG.md, media_kit/README.md, media_kit/pubspec.yaml, media_kit_video/CHANGELOG.md, media_kit_video/pubspec.yaml
=> build: bump project version to v1.1.0

README.md, media_kit/README.md, media_kit_video/lib/src/subtitle/subtitle_view.dart, media_kit_video/lib/src/video/video_texture.dart, media_kit_video/lib/src/video/video_web.dart
Working as intended on Android.
_Probably poor-naming._
=> feat: `pauseUponEnteringBackgroundMode`

media_kit_test/lib/main.dart, media_kit_test/lib/tests/04.tabs_test.dart, media_kit_test/lib/tests/09.seamless.dart
For teaching mediocre programmers about optimization.
https://github.com/media-kit/media-kit/assets/28951144/52260678-73a4-4d66-9a46-3a93919a0421
=> example: `PageView` seamless `Video` transition sample

media_kit_video/CHANGELOG.md, media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift
=> fix(darwin): remove black screen when switching videos

libs/android/media_kit_libs_android_audio/CHANGELOG.md, libs/android/media_kit_libs_android_audio/android/build.gradle, libs/android/media_kit_libs_android_audio/example/README.md, libs/android/media_kit_libs_android_audio/pubspec.yaml, libs/android/media_kit_libs_android_video/CHANGELOG.md, libs/android/media_kit_libs_android_video/android/build.gradle, libs/android/media_kit_libs_android_video/example/README.md, libs/android/media_kit_libs_android_video/pubspec.yaml, libs/windows/media_kit_libs_windows_audio/CHANGELOG.md, libs/windows/media_kit_libs_windows_audio/example/README.md, libs/windows/media_kit_libs_windows_audio/pubspec.yaml, libs/windows/media_kit_libs_windows_audio/windows/CMakeLists.txt, libs/windows/media_kit_libs_windows_video/CHANGELOG.md, libs/windows/media_kit_libs_windows_video/example/README.md, libs/windows/media_kit_libs_windows_video/pubspec.yaml, libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt
=> build(windows/android): bump dependencies

media_kit/lib/src/player/native/player/real.dart, media_kit_video/lib/media_kit_video.dart, media_kit_video/lib/src/video_controller/android_video_controller/real.dart, media_kit_video/lib/src/video_controller/android_video_controller/stub.dart, media_kit_video/lib/src/video_controller/native_video_controller/real.dart, media_kit_video/lib/src/video_controller/native_video_controller/stub.dart, media_kit_video/lib/src/video_controller/platform_video_controller.dart, media_kit_video/lib/src/video_controller/video_controller.dart, media_kit_video/lib/src/video_controller/web_video_controller/real.dart, media_kit_video/lib/src/video_controller/web_video_controller/stub.dart
- feat(android): `VideoControllerConfiguration.scale`
- fix(android): use `hwdec=auto`
- fix(android): `SurfaceTexture.setDefaultBufferSize` & render race
=> fix(android): SurfaceTexture.setDefaultBufferSize & render race; fix(android): use hwdec=auto; feat(android): VideoControllerConfiguration.scale;

README.md, libs/ios/media_kit_libs_ios_audio/CHANGELOG.md, libs/ios/media_kit_libs_ios_audio/example/README.md, libs/ios/media_kit_libs_ios_audio/ios/Makefile, libs/ios/media_kit_libs_ios_audio/pubspec.yaml, libs/ios/media_kit_libs_ios_video/CHANGELOG.md, libs/ios/media_kit_libs_ios_video/example/README.md, libs/ios/media_kit_libs_ios_video/ios/Makefile, libs/ios/media_kit_libs_ios_video/pubspec.yaml, libs/macos/media_kit_libs_macos_audio/CHANGELOG.md, libs/macos/media_kit_libs_macos_audio/example/README.md, libs/macos/media_kit_libs_macos_audio/macos/Makefile, libs/macos/media_kit_libs_macos_audio/pubspec.yaml, libs/macos/media_kit_libs_macos_video/CHANGELOG.md, libs/macos/media_kit_libs_macos_video/example/README.md, libs/macos/media_kit_libs_macos_video/macos/Makefile, libs/macos/media_kit_libs_macos_video/pubspec.yaml, media_kit/CHANGELOG.md, media_kit/README.md, media_kit/pubspec.yaml
=> build(darwin): bump dependencies

libs/android/media_kit_libs_android_audio/android/src/main/java/com/alexmercerind/media_kit_libs_android_audio/MediaKitLibsAndroidAudioPlugin.java, libs/android/media_kit_libs_android_video/android/src/main/java/com/alexmercerind/media_kit_libs_android_video/MediaKitLibsAndroidVideoPlugin.java, media_kit/lib/src/player/native/player/real.dart, media_kit/lib/src/player/native/utils/find_packages.dart, media_kit_video/android/src/main/java/com/alexmercerind/media_kit_video/MediaKitVideoPlugin.java, media_kit_video/android/src/main/java/com/alexmercerind/media_kit_video/VideoOutput.java, media_kit_video/android/src/main/java/com/alexmercerind/media_kit_video/VideoOutputManager.java, media_kit_video/lib/src/video_controller/android_video_controller/real.dart
- Intercept `SurfaceTexture.setOnFrameAvailableListener`.
- Notify first frame through `MethodChannel`.
- Acquire `FlutterJNI` reference using Java reflection.
- Call `FlutterJNI.markTextureFrameAvailable`.
=> feat(android): re-implement `waitUntilFirstFrameRenderedNotify` API (#349)

libs/ios/media_kit_libs_ios_audio/ios/Makefile, libs/ios/media_kit_libs_ios_video/ios/Makefile, libs/macos/media_kit_libs_macos_audio/macos/Makefile, libs/macos/media_kit_libs_macos_video/macos/Makefile
=> build(darwin): bump libs

README.md, libs/android/media_kit_libs_android_audio/README.md, libs/android/media_kit_libs_android_audio/pubspec.yaml, libs/android/media_kit_libs_android_video/README.md, libs/android/media_kit_libs_android_video/pubspec.yaml, libs/ios/media_kit_libs_ios_audio/README.md, libs/ios/media_kit_libs_ios_audio/pubspec.yaml, libs/ios/media_kit_libs_ios_video/README.md, libs/ios/media_kit_libs_ios_video/pubspec.yaml, libs/linux/media_kit_libs_linux/README.md, libs/linux/media_kit_libs_linux/pubspec.yaml, libs/macos/media_kit_libs_macos_audio/README.md, libs/macos/media_kit_libs_macos_audio/pubspec.yaml, libs/macos/media_kit_libs_macos_video/README.md, libs/macos/media_kit_libs_macos_video/pubspec.yaml, libs/universal/media_kit_libs_audio/README.md, libs/universal/media_kit_libs_audio/pubspec.yaml, libs/universal/media_kit_libs_video/README.md, libs/universal/media_kit_libs_video/pubspec.yaml, libs/windows/media_kit_libs_windows_audio/README.md, libs/windows/media_kit_libs_windows_audio/pubspec.yaml, libs/windows/media_kit_libs_windows_video/README.md, libs/windows/media_kit_libs_windows_video/pubspec.yaml, media_kit/README.md, media_kit/pubspec.yaml, media_kit_native_event_loop/README.md, media_kit_native_event_loop/pubspec.yaml, media_kit_video/README.md, media_kit_video/pubspec.yaml
I've decided to remove my funding URLs from all README(s) & pubspec.yaml(s). I hope I didn't miss any.
[My username is still present in `FUNDING.yml`](https://github.com/media-kit/media-kit/blob/main/.github/FUNDING.yml). Other [project contributors](https://github.com/media-kit/media-kit/graphs/contributors) can easily add themselves!
Hopefully update for nearly all packages is due & change will be rolled out easily.
<hr>
First of all, I'm happy with the support I received during difficult early stage development.
It must be remembered that this is neither a company nor a business. It's just bunch of code released publicly under free & open-source license without any warranty or liability. There are multiple authors to this project.
I started this project & I realize I've become very …
=> chore: remove funding URL(s) [skip ci]

media_kit_test/lib/tests/04.tabs_test.dart, media_kit_test/lib/tests/05.stress_test.dart, media_kit_test/lib/tests/07.video_controller_set_size.dart, media_kit_test/lib/tests/09.seamless.dart
=> fix(test/seamless): fix players lifecycle

media_kit_video/common/darwin/Classes/plugin/TextureSW.swift, media_kit_video/ios/Classes/plugin/TextureHW.swift, media_kit_video/macos/Classes/plugin/TextureHW.swift
- fix `mpv_render_context_free` crash (#480)
=> fix(video): fix mpv_render_context_free call

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart
Reverts media-kit/media-kit#495
=> Revert "feat(material-seekbar): Center the seek bar within its parent container for improved tap area"

README.md, media_kit/CHANGELOG.md, media_kit/README.md, media_kit/pubspec.yaml, media_kit_video/CHANGELOG.md, media_kit_video/lib/media_kit_video_controls/src/controls/methods/video_state.dart, media_kit_video/lib/media_kit_video_controls/src/controls/widgets/video_state_inherited_widget.dart, media_kit_video/lib/src/video/video_web.dart, media_kit_video/lib/src/video_view_parameters.dart, media_kit_video/pubspec.yaml, video_player_media_kit/CHANGELOG.md, video_player_media_kit/README.md, video_player_media_kit/pubspec.yaml
=> fix(web): compilation error

media_kit_video/lib/media_kit_video_controls/src/controls/extensions/duration.dart, media_kit_video/lib/media_kit_video_controls/src/controls/material.dart
- `gesturesEnabledWhileControlsVisible`: Enables or disables gesture controls like volume and brightness adjustments when media controls are visible. 
> Note: This option is ignored when gestures are disabled.
- `seekOnDoubleTapEnabledWhileControlsVisible`: Allows the double-tap to seek feature to work when the media controls are visible.
> Note: This option is effective only when `seekOnDoubleTap` is true.
- `gestureSensitivity`: Configures the sensitivity level of gestures like volume and brightness adjustments. The higher the value, the less sensitive the gestures will be.
- Updated conditionals for handling gesture sensitivity and state-dependent features.
- Minor code comments and formatting updates.
This PR introduces new variables that enhance the user experience by offering more …
=> Customize controls

video_player_media_kit/CHANGELOG.md, video_player_media_kit/README.md, video_player_media_kit/lib/src/media_kit_video_player.dart, video_player_media_kit/pubspec.yaml
=> fix(video_player_media_kit): `VideoPlayerValue.size` stuck at `Size.zero` after `VideoEventType.initialized`

.github/workflows/ci.yml, media_kit_video/lib/media_kit_video_controls/src/controls/material.dart
fixes: https://github.com/media-kit/media-kit/commit/e01d5344135922289d38a709639a686d92d1a531#commitcomment-132285038
=> feat: speed up on long press

CODE_OF_CONDUCT.md
Everyone gotta behave in this repository from now on (most importantly me).
=> chore: code of conduct

media_kit_video/common/darwin/Classes/plugin/VideoOutput.swift
Not just `registry.register` must run on the main thread, but also `registry.unregisterTexture`, `registry.textureFrameAvailable`, and the `MethodChannel` within `textureUpdateCallback`.
I used synchronous block where possible as it makes the memory model lot more clear, and we don't really want or need this stuff to start queueing up in the background.
This will actually fix #590 on iOS, that warning from flutter is about channel usage, not texture registry.
This stuff should be prioritized to change on any other affected platforms if possible, it causes some real crashes
=> [darwin] Run all engine callbacks on the main queue

libs/ios/media_kit_libs_ios_audio/ios/create_framework_symlinks.sh, libs/ios/media_kit_libs_ios_video/ios/create_framework_symlinks.sh, libs/macos/media_kit_libs_macos_audio/macos/create_framework_symlinks.sh, libs/macos/media_kit_libs_macos_video/macos/create_framework_symlinks.sh
`-f` must be a comma-separated list.
Fix #709.
Thx @hndrbrm.
=> Fix use of the darwin version of cut during build

.github/workflows/ci.yml
fix ci for android by setup java 
use flutter action v2 and use its caching to improve speed
=> chore: fix ci for android and added caching to improve speed

media_kit/lib/src/player/native/player/real.dart
setting cache to yes instead of auto, since in some cases the cache were not working on some sources 
it can be set in users apps, but the default i think should be with cache enabled on all sources
=> chore: set cache to yes

media_kit_test/lib/main.dart, media_kit_test/lib/tests/12.custom_mobile_controls.dart, media_kit_test/lib/tests/13.custom_desktop_controls.dart, media_kit_test/lib/tests/14.custom_adaptive_controls.dart, media_kit_test/lib/tests/15.full_screen_player.dart
- Added new test files for custom controls:
- `12.custom_mobile_controls.dart`
- `13.custom_desktop_controls.dart`
- `14.custom_adaptive_controls.dart`
=> chore: adding custom controls examples.

libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt, media_kit_native_event_loop/src/CMakeLists.txt, media_kit_video/windows/CMakeLists.txt
=> Workaround for broken windows builds

libs/android/media_kit_libs_android_audio/android/build.gradle, libs/android/media_kit_libs_android_video/android/build.gradle
improving android gradle to be like windows logic, fixing https://github.com/media-kit/media-kit/issues/645
=> fix: new gradle logic for downloading

media_kit_video/lib/src/utils/wakelock.dart
=> fix: wakelock print

media_kit_test/.metadata, media_kit_test/android/.gitignore, media_kit_test/android/app/build.gradle, media_kit_test/android/app/src/debug/AndroidManifest.xml, media_kit_test/android/app/src/main/AndroidManifest.xml, media_kit_test/android/app/src/main/kotlin/com/alexmercerind/media_kit_test/MainActivity.kt, media_kit_test/android/app/src/main/kotlin/com/github/alexmercerind/media_kit_test/MainActivity.kt, media_kit_test/android/app/src/profile/AndroidManifest.xml, media_kit_test/android/build.gradle, media_kit_test/android/gradle.properties, media_kit_test/android/gradle/wrapper/gradle-wrapper.properties, media_kit_test/android/settings.gradle
hopefully fixing the android ci, but we will see
=> chore: migrate android files to latest changes

CHANGELOG.md, libs/android/media_kit_libs_android_audio/CHANGELOG.md, libs/android/media_kit_libs_android_audio/pubspec.yaml, libs/android/media_kit_libs_android_video/CHANGELOG.md, libs/android/media_kit_libs_android_video/pubspec.yaml, libs/linux/media_kit_libs_linux/CHANGELOG.md, libs/linux/media_kit_libs_linux/pubspec.yaml, libs/universal/media_kit_libs_audio/CHANGELOG.md, libs/universal/media_kit_libs_audio/pubspec.yaml, libs/universal/media_kit_libs_video/CHANGELOG.md, libs/universal/media_kit_libs_video/pubspec.yaml, libs/windows/media_kit_libs_windows_video/CHANGELOG.md, libs/windows/media_kit_libs_windows_video/pubspec.yaml, media_kit/CHANGELOG.md, media_kit/pubspec.yaml, media_kit_video/CHANGELOG.md, media_kit_video/pubspec.yaml, video_player_media_kit/CHANGELOG.md, video_player_media_kit/example/pubspec.yaml, video_player_media_kit/pubspec.yaml
- media_kit@1.2.0
- media_kit_libs_android_audio@1.3.7
- media_kit_libs_android_video@1.3.7
- media_kit_libs_linux@1.2.1
- media_kit_libs_windows_video@1.0.11
- media_kit_video@1.3.0
- video_player_media_kit@1.0.6
- media_kit_libs_audio@1.0.6
- media_kit_libs_video@1.0.6
Auto generated by melos, we can clean it up for an easier understanding
=> chore(release): publish packages

media_kit_video/lib/media_kit_video_controls/src/controls/material.dart
Set the directionality of the video player to left-to-right to correct the animation display.
fixes https://github.com/media-kit/media-kit/issues/1108
=> Fix video player animation directionality issue

media_kit/lib/src/models/media/media_web.dart, media_kit/lib/src/player/native/player/real.dart, media_kit/test/src/player/player_test.dart
https://github.com/media-kit/media-kit/pull/1036#issuecomment-2481607404
=> fix: playlist state/stream not being updated by `setShuffle` in `NativePlayer`

media_kit/lib/src/player/native/player/real.dart, media_kit/lib/src/player/web/player/real.dart
`current` value not synchronously  updated with `playlist` state which leads to potential issues.
fix: #1167
=> fix:Playlist Updates Incorrectly in Certain Scenarios

README.md, media_kit/lib/src/models/player_state.dart, media_kit/lib/src/models/player_stream.dart, media_kit/lib/src/player/native/player/real.dart, media_kit/lib/src/player/platform_player.dart, media_kit/lib/src/player/web/player/real.dart, media_kit/test/src/models/media/player_state_test.dart, media_kit/test/src/player/player_test.dart
=> feat: Adding state and stream of shuffle

media_kit_video/linux/media_kit_video_plugin.cc
part of #1212
Using `g_idle_add` to schedule method call on the GTK main thread.
=> fix[linux]: run method call on main thread

media_kit/lib/src/player/native/player/real.dart
=> fix(android): use video-params instead of video-output-params
